
server:
  port: 8080
spring:
  application:
    name: app
  datasource:
    url: jdbc:mysql://192.168.107.7/app?useUnicode=yes&characterEncoding=utf-8&useOldAliasMetadataBehavior=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 3nodapp
    driver_class_namel: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    keepAlive: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
debug: true
logging:
  level:
     snod.com.cn.dao : debug

