package snod.com.cn.dao;

import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

import snod.com.cn.entity.UserInfo;

@Mapper
public interface UserDao {
	public String countByExample();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public String deleteByExample();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public String insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public UserInfo selectByExample(int userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public String updateByExample();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(UserInfo record);

	public UserInfo selectByPrimaryKey(int userId);
	
	public void updateUserInfo(UserInfo uinfo);

	public int editUserInfo(UserInfo userInfo);
}
